# Generated by Django 3.2.9 on 2022-02-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20220208_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='foreignUrl',
            field=models.URLField(blank=True, unique=True, verbose_name='外部图片链接'),
        ),
    ]
