# update on 2022.2.15
Django: 3.2.12 # 4.0.2部分第三方库未支持
colorama: 0.4.4
django-recaptcha: 3.0.0
fabric: 2.6.0
gunicorn: 20.1.0
faker: 12.3.0
django-jazzmin: 2.4.9
django-haystack: 3.1.1
mysqlclient: 2.1.0
django-user-agents: 0.4.0
Markdown: 3.3.6
coverage: 6.3.1
requests: 2.27.1
jieba: 0.42.1
selenium: 4.1.0
webdriver-manager: 3.5.2
SpeechRecognition: 3.8.1
pymemcache: 3.5.0
moviepy: 1.0.3
pydub: 0.25.1
numpy: 1.22.2
autopep8: 1.6.0
django-pure-pagination: 0.3.0
Whoosh: 2.7.4
python-dotenv: 0.19.2
django-cors-headers: 3.11.0
django-cors-middleware: 1.5.0
Pillow: 9.0.1
ipython: 8.0.1
sh: 1.14.2
qcloudsms-py: 0.1.4
redis: 4.1.3
django-redis: 5.2.0
djangorestframework: 3.13.1
django-filter: 21.1
django-import-export: 2.7.1
django-qiniu-storage: 7.5.0
sqlite3-to-mysql: 1.4.9
mysql-to-sqlite3: 1.4.10
pipdeptree: 2.2.1
fake-useragent: 0.1.11
django-debug-toolbar: 3.2.4
